services:
  pigallery2:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /exifapi/start.sh
    container_name: pigallery2_metadata_editor
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
    volumes:
      - ./exifapi/ui:/exifapi/ui     # static files as volume
      - "/Users/kay.agahd/Downloads/PigalleryExifTest/TestBilder/data2/db:/app/data/db"
      - "/Users/kay.agahd/Downloads/PigalleryExifTest/TestBilder/data2/config:/app/data/config" # CHANGE ME
      - "/Users/kay.agahd/Downloads/PigalleryExifTest/TestBilder/data2/tmp:/app/data/tmp" # CHANGE ME
      - "/Users/kay.agahd/Downloads/PigalleryExifTest/TestBilder/Fotos:/app/data/images/Fotos"
    ports:
      - 9088:80    # PiGallery2 external:internal ports
      - 9089:9089  # Metadata-API external:internal ports
    restart: unless-stopped

