services:
  pigallery2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pigallery2_metadata_editor
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
    volumes:
      - ./exifapi/ui:/exifapi/ui                         # static files as volume
      - "<YOUR_PIGALLERY2_DB_PATH>:/app/data/db"         # CHANGE ME
      - "<YOUR_PIGALLERY2_CONFIG_PATH>:/app/data/config" # CHANGE ME
      - "<YOUR_PIGALLERY2_TMP_PATH>:/app/data/tmp"       # CHANGE ME
      - "<YOUR_PIGALLERY2_IMAGES_PATH>:/app/data/images" # CHANGE ME
    ports:
      - 9088:80    # PiGallery2 external:internal ports
      - 9090:9090  # Metadata-API external:internal ports
    restart: unless-stopped

